### ISSUE TITLE
Crash when using M&B Battlegear 2's dual wield ability

### ISSUE THREAD

**Issue by AnonymousPuppy** [Alex-hawks/Sanguine-Extras#3]
Urgent bug report here! Using a custom modpack, forge .1240, and sanguine utilities 1.2.1. Whenever I press a button to pull out my left hand, my game crashes and I am unable to load the world up again. Mine and Blade Battlegear 2 is the mod that adds this functionality, allowing you to pull out your second arm to dual wield weapons. Regardless of which key I have the ability binded to, it always crashes. 

Here is the crash report: http://pastebin.com/wE8zQb0z

Please fix this ASAP, thank you :)

**Comment by Alex-hawks** [comment]
I need a version to put in my dev environment

**Comment by AnonymousPuppy** [comment]
If you're referring to Battlegear 2, then you can get it here: http://minecraft.curseforge.com/mc-mods/59710-mb-battlegear-2/files

**Comment by AnonymousPuppy** [comment]
Any fix?

**Comment by Alex-hawks** [comment]
working on it, trying to fix it

**Comment by Alex-hawks** [comment]
http://puu.sh/eqaPp/19e16ceb21.jpg next version

**Comment by AnonymousPuppy** [comment]
Any idea when the next version will be released?

**Comment by Alex-hawks** [comment]
When I finish the Sanguine Chest. It currently needs textures based on the slates
