### ISSUE TITLE
Mod interaction crash when firing water projectile from Project E Evertide Amulet

### ISSUE THREAD

**Issue by mccoole** [Alex-hawks/Sanguine-Extras#4]
The crash seems to indicate an issue in Sanguine Utilities though so I wanted to report it here. It also causes the world to be un-loadable until I roll it back, producing the same error on login.  Removing Sanguine Utilities seems to fix the issue but I really wanted to play around with it if possible.  Here's the crash file:  http://pastebin.com/Mrf81GER  Thanks!

**Comment by Alex-hawks** [comment]
I have fixed a very similar crash in the code, leaving this open just in case. Tell me if it persists after the next version

**Comment by Alex-hawks** [comment]
closing due to no response
